name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Clone
      uses: actions/checkout@v4

    - name: ⚒️ Build
      run: dotnet publish -c Release --self-contained true -r linux-x64

    - name: 📤 Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: Binaries
        path: ./bin/Release/net6.0/linux-x64/publish
        retention-days: 1
